### ISSUE TITLE
Runtime

### ISSUE THREAD

**Issue by saskra** [pcpLiu/DeepSeqPan#1]
What is the runtime on your hardware? Unfortunately, I do not have access to a GPU architecture at the moment and on CPU the standard training example "python runner.py --train" takes nearly one hour for each of the 1000 epochs - which is not feasible here.

**Comment by pcpLiu** [comment]
Hi @saskra , we scheduled our training on a Titan X GPU.

**Comment by saskra** [comment]
And how long did that take?

**Comment by pcpLiu** [comment]
I just checked the log, it took about 40s to finish an epoch.
