### ISSUE TITLE
How to evaluate/ test?

### ISSUE THREAD

**Issue by saskra** [pcpLiu/DeepSeqPan#3]
Me again. Training model on own data finally done. But how to use it on my own test data set? Seems there are more hard coded parts to change in the source code than I have found until now...

**Comment by pcpLiu** [comment]
Hey @saskra . Glad hearing that you finished the training.

If you just want to test on a list of input,  you can write a simple script referring following codes:
1. Encode peptide and HLA sequence. [this function](https://github.com/pcpLiu/DeepSeqPan/blob/364191be88dcc93db07eab72b02319271d04d608/scripts/data_provider.py#L89) and [this one](https://github.com/pcpLiu/DeepSeqPan/blob/364191be88dcc93db07eab72b02319271d04d608/scripts/data_provider.py#L122)
2. Load model: [here](https://github.com/pcpLiu/DeepSeqPan/blob/364191be88dcc93db07eab72b02319271d04d608/scripts/eval.py#L402)
3. Eval: [here](https://github.com/pcpLiu/DeepSeqPan/blob/364191be88dcc93db07eab72b02319271d04d608/scripts/eval.py#L218)

Also, I will upload a script to support this testing later this week. Hope it helps

**Comment by pcpLiu** [comment]
Hi @saskra 

Sorry for late update. Just added a simple [testing script](https://github.com/pcpLiu/DeepSeqPan/blob/master/scripts/test.py). If you still need it, you can try. 
The usage is listed [here](https://github.com/pcpLiu/DeepSeqPan/tree/master/scripts#test)
